apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  params:
    - name: greeting
      default: Hello World
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    capabilities:
      drop: ["ALL"]
  steps:
    - name: echo
      image: alpine
      securityContext:
        runAsUser: 1001
      script: |
        #!/bin/sh
        echo "$(params.greeting)"
